/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.balnave.rambler.gui;

import com.balnave.rambler.Config;
import com.balnave.rambler.Rambler;
import com.balnave.rambler.Result;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author balnave
 */
public class RamblerFrame extends javax.swing.JFrame {

    private Rambler rambler;

    /**
     * Creates new form RamblerFrame
     */
    public RamblerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        maxThreads = new javax.swing.JSpinner();
        maxThreadsLabel = new javax.swing.JLabel();
        siteUrlLabel = new javax.swing.JLabel();
        siteUrl = new javax.swing.JTextField();
        includesRegexp = new javax.swing.JTextField();
        includesRegexpLabel = new javax.swing.JLabel();
        excludesRegexpLabel = new javax.swing.JLabel();
        excludesRegexp = new javax.swing.JTextField();
        progress = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        rambleBtn = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(maxThreads, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 50, -1));

        maxThreadsLabel.setText("Threads");
        getContentPane().add(maxThreadsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 93, -1, -1));

        siteUrlLabel.setText("Site URL");
        getContentPane().add(siteUrlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 49, -1));
        getContentPane().add(siteUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 11, 308, -1));

        includesRegexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                includesRegexpActionPerformed(evt);
            }
        });
        getContentPane().add(includesRegexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 37, 308, -1));

        includesRegexpLabel.setText("Includes");
        getContentPane().add(includesRegexpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        excludesRegexpLabel.setText("Excludes");
        getContentPane().add(excludesRegexpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));
        getContentPane().add(excludesRegexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 63, 307, -1));
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 123, 303, -1));

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "URL", "Content Type", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(resultsTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 610, 275));

        rambleBtn.setText("Start Ramble!");
        rambleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rambleBtnMouseClicked(evt);
            }
        });
        rambleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rambleBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rambleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void includesRegexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_includesRegexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_includesRegexpActionPerformed

    private void rambleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rambleBtnActionPerformed
        boolean isSelected = rambleBtn.isSelected();
        rambleBtn.setText(isSelected ? "Stop Ramble!" : "Start Ramble!");
        if (isSelected) {
            Config rConfig = new Config(siteUrl.getText(), includesRegexp.getText(), excludesRegexp.getText());
            rConfig.setMaxResultCount(50);
            rConfig.setMaxThreadCount(20);
            try {
                rambler = new Rambler(rConfig);
                DefaultTableModel model = new DefaultTableModel();

                // Create a couple of columns 
                model.addColumn("Status");
                model.addColumn("Content Type");
                model.addColumn("URL");
                model.addColumn("Mssage");

                // Append a row 
                for(Result result : rambler.getResults()){
                    model.addRow(new Object[]{result.getResponseStatus(), result.getContentType(), result.getRequestUrl(), result.getResponseMessage()});
                }
                resultsTable.setModel(model);
            } catch (Exception ex) {
                Logger.getLogger(RamblerFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (rambler != null) {
            rambler.setForceStop(true);
        }
    }//GEN-LAST:event_rambleBtnActionPerformed

    private void rambleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rambleBtnMouseClicked
    }//GEN-LAST:event_rambleBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RamblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RamblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RamblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RamblerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RamblerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField excludesRegexp;
    private javax.swing.JLabel excludesRegexpLabel;
    private javax.swing.JTextField includesRegexp;
    private javax.swing.JLabel includesRegexpLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner maxThreads;
    private javax.swing.JLabel maxThreadsLabel;
    private javax.swing.JProgressBar progress;
    private javax.swing.JToggleButton rambleBtn;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextField siteUrl;
    private javax.swing.JLabel siteUrlLabel;
    // End of variables declaration//GEN-END:variables
}
